Get this module be compatible with lower version of perls
FractalBoy/perl-language-server pull request #43
Opened 2021-06-30 15:17 UTC by stphnlyd

With Perl::MinimumVersion I see with the changes now it could be compatible with Perl 5.14, but I would set Perl 5.26 as min version now as I have only 5.26

2021-06-30 22:27 UTC, FractalBoy requested changes

2021-07-01 14:26 UTC, stphnlyd commented
updated

2021-07-01 14:28 UTC, FractalBoy approved these changes

2021-07-01 14:28 UTC, FractalBoy commented
I'll do some testing and then I'll merge and release later today.

Thanks!

2021-07-01 16:48 UTC, FractalBoy commented
Signature help and finding pod links still appear to work as expected. Thanks!

2021-07-01 16:49 UTC, merged