Add documentation for using PLS with Neovim
FractalBoy/perl-language-server pull request #49
Opened 2021-07-05 20:38 UTC by WhoIsSethDaniel

2021-07-05 20:38 UTC, WhoIsSethDaniel commented
ref: #48

2021-07-05 20:48 UTC, FractalBoy commented
The way you documented it implies that those configuration settings aren't available in Neovim.

There should probably be two separate `setup` sections - one for VSCode (just install the extension) and one for Neovim (your instructions)

2021-07-05 20:53 UTC, WhoIsSethDaniel commented
I'll fiddle with it later today and resubmit. Thanks.

2021-07-05 21:32 UTC, FractalBoy commented
Also, please update the POD to mention that PLS has been tested on Neovim as well:

https://github.com/WhoIsSethDaniel/perl-language-server/blob/b7927280209565bc74bae4d7fcb986628dc42c2f/server/lib/PLS.pm#L79-L82

2021-07-06 02:40 UTC, WhoIsSethDaniel commented
I updated the POD. I added a Setup section that includes the steps specific to  VSCode and Neovim.

2021-07-06 13:38 UTC, FractalBoy requested changes
Looking better - one more small suggestion.

2021-07-06 13:38 UTC, FractalBoy commented on README.md
> +This assumes Neovim 0.5.0 or greater and that you have [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) installed.
```suggestion
This assumes Neovim 0.5.0 or greater.

Install [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig).
```

2021-07-06 15:00 UTC, WhoIsSethDaniel commented
Added suggested change.

2021-07-06 15:03 UTC, FractalBoy approved these changes

2021-07-06 15:04 UTC, merged